plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.key'
    compileSdk 36

    defaultConfig {
        minSdk 24
        targetSdk 36
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    api('com.singular.sdk:singular_sdk:12.10.0') {
        exclude group: 'androidx.fragment', module: 'fragment'
    }
}