plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.key'
    compileSdk rootProject.ext.targetSdkVersion

    defaultConfig {
        minSdk 24
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = "21"
    }
    lint {
        targetSdk rootProject.ext.targetSdkVersion
    }
    testOptions {
        targetSdk rootProject.ext.targetSdkVersion
    }
}

dependencies {
    api('com.singular.sdk:singular_sdk:12.10.0') {
        exclude group: 'androidx.fragment', module: 'fragment'
    }

    api(libs.adjust)
}