plugins {
    id "com.android.library"
}

android {
    compileSdk rootProject.ext.targetSdkVersion
    namespace 'com.king.drawboard'

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
        debug {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError false
        warning 'InvalidPackage'
        targetSdk rootProject.ext.targetSdkVersion
    }
    testOptions {
        targetSdk rootProject.ext.targetSdkVersion
    }

}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
